version: "3"
services:
  postgresql:
    image: mdillon/postgis:9.6-alpine
    command: ["postgres", "-c", 'listen_addresses="*"', "-c", "fsync=off"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5400:5432"
